<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Condition="'$(VersionNumber)' == ''">
		<VersionNumber>3.1-debug</VersionNumber>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFrameworks>net10.0;net48;netstandard2.0</TargetFrameworks>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>SanteDB.BI</PackageId>
		<Title>SanteDB.BI</Title>
		<Version>$(VersionNumber)</Version>
		<Description>SanteDB Business Intelligence (BI) core logic. Provides structures for data sources, queries, reports, and report controls rendered in all SanteDB software solutions.</Description>
		<Authors>SanteSuite Contributors</Authors>
		<PackageTags>SanteDB</PackageTags>
		<RepositoryUrl>https://github.com/santedb/santedb-bi</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeSymbols>true</IncludeSymbols>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<Product>SanteDB</Product>
		<Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
		<Company>SanteSuite Contributors</Company>
		<PackageIconUrl>http://santesuite.org/assets/img/logo.png</PackageIconUrl>
		<PackageProjectUrl>http://santesuite.org</PackageProjectUrl>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Include="Resources\xlsxwork.xsl" />
		<EmbeddedResource Include="Resources\excel-xml.xsl" />
		<EmbeddedResource Include="Resources\csv.xsl" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.1" />
		<PackageReference Include="DynamicExpresso.Core" Version="2.17.2" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\SanteDB.licenseheader">
			<Link>SanteDB.licenseheader</Link>
		</None>
		<None Include="Schema\BusinessIntelligence.xsd">
			<SubType>Designer</SubType>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Include="Schema\xhtml.xsd">
			<SubType>Designer</SubType>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<Choose>
		<When Condition="$(SolutionName.Contains('-nuget'))">
			<ItemGroup>
				<PackageReference Include="SanteDB.Core.Api" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Applets" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Model" Version="$(VersionNumber)" />
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<ProjectReference Include="..\..\santedb-api\SanteDB.Core.Api\SanteDB.Core.Api.csproj">
				</ProjectReference>
				<ProjectReference Include="..\..\santedb-applets\SanteDB.Core.Applets\SanteDB.Core.Applets.csproj">
				</ProjectReference>
				<ProjectReference Include="..\..\santedb-model\SanteDB.Core.Model\SanteDB.Core.Model.csproj">
				</ProjectReference>
			</ItemGroup>
		</Otherwise>
	</Choose>
</Project>